/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursework.translator.gui;

import coursework.translator.manager.StaticFormActions;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Admin
 */
public class PreferencesGui extends javax.swing.JFrame {

    /**
     * Creates new form Preferences
     */
    private String classTablePath;
    private String lexicTablePath;
    private String stateTablePath;
    private String sourceCodePath;
    private String priorityTablePath;
    private String stackWriterTablePath;
    private Speaker speaker;

    public PreferencesGui(String classTablePath, String lexicTablePath, String stateTablePath,
            String priorityTablePath, String stackWriterTablePath) {
        initComponents();
        speaker = new Speaker();
        this.classTablePath = classTablePath;
        this.lexicTablePath = lexicTablePath;
        this.stateTablePath = stateTablePath;
        this.priorityTablePath = priorityTablePath;
        this.stackWriterTablePath = stackWriterTablePath;
        jTextFieldClassTablePath.setText(classTablePath);
        jTextFieldLexicTablePath.setText(lexicTablePath);
        jTextFieldPriorityTablePath.setText(priorityTablePath);
        jTextFieldStackTablePath.setText(stackWriterTablePath);
        jTextFieldStateTablePath.setText(stateTablePath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonClassTableChoose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldClassTablePath = new javax.swing.JTextField();
        jButtonLexicTableChoose = new javax.swing.JButton();
        jTextFieldLexicTablePath = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonStateTableChoose = new javax.swing.JButton();
        jTextFieldStateTablePath = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonPriorityTableChoose = new javax.swing.JButton();
        jTextFieldPriorityTablePath = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonStackTableChoose = new javax.swing.JButton();
        jTextFieldStackTablePath = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");

        jButtonClassTableChoose.setText("Choose");
        jButtonClassTableChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassTableChooseActionPerformed(evt);
            }
        });

        jLabel1.setText("Class table:");

        jLabel7.setText("Lexic table:");

        jTextFieldClassTablePath.setEditable(false);
        jTextFieldClassTablePath.setText("TablePath");

        jButtonLexicTableChoose.setText("Choose");
        jButtonLexicTableChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLexicTableChooseActionPerformed(evt);
            }
        });

        jTextFieldLexicTablePath.setEditable(false);
        jTextFieldLexicTablePath.setText("TablePath");

        jLabel8.setText("State table:");

        jButtonStateTableChoose.setText("Choose");
        jButtonStateTableChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStateTableChooseActionPerformed(evt);
            }
        });

        jTextFieldStateTablePath.setEditable(false);
        jTextFieldStateTablePath.setText("TablePath");

        jLabel9.setText("Priority table:");

        jButtonPriorityTableChoose.setText("Choose");
        jButtonPriorityTableChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPriorityTableChooseActionPerformed(evt);
            }
        });

        jTextFieldPriorityTablePath.setEditable(false);
        jTextFieldPriorityTablePath.setText("TablePath");

        jLabel10.setText("Stack table:");

        jButtonStackTableChoose.setText("Choose");
        jButtonStackTableChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStackTableChooseActionPerformed(evt);
            }
        });

        jTextFieldStackTablePath.setEditable(false);
        jTextFieldStackTablePath.setText("TablePath");

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldStateTablePath, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPriorityTablePath, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPriorityTableChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonStateTableChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldClassTablePath, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldLexicTablePath, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jTextFieldStackTablePath, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonStackTableChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jButtonClassTableChoose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLexicTableChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClassTableChoose)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldClassTablePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldLexicTablePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLexicTableChoose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldStateTablePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStateTableChoose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPriorityTablePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPriorityTableChoose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldStackTablePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStackTableChoose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClassTableChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassTableChooseActionPerformed
        classTablePath = choose(classTablePath, "classtable");
    }//GEN-LAST:event_jButtonClassTableChooseActionPerformed

    private void jButtonLexicTableChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLexicTableChooseActionPerformed
        lexicTablePath = choose(lexicTablePath, "lexictable");
    }//GEN-LAST:event_jButtonLexicTableChooseActionPerformed

    private void jButtonStateTableChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStateTableChooseActionPerformed
        stateTablePath = choose(stateTablePath, "lst");
    }//GEN-LAST:event_jButtonStateTableChooseActionPerformed

    private void jButtonPriorityTableChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPriorityTableChooseActionPerformed
        priorityTablePath = choose(priorityTablePath, "pt");
    }//GEN-LAST:event_jButtonPriorityTableChooseActionPerformed

    private void jButtonStackTableChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStackTableChooseActionPerformed
        stackWriterTablePath = choose(stackWriterTablePath, "wts");
    }//GEN-LAST:event_jButtonStackTableChooseActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        speaker.performAction(StaticFormActions.buttonSave);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private String choose(String defaults, final String ext) {
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(this);
        jfc.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isFile()) {
                    return f.getName().contains("." + ext);
                }
                return false;
            }

            @Override
            public String getDescription() {
                return "FAS sourcecode files";
            }
        }
        );
        File t = jfc.getSelectedFile();
        if (t == null) {
            JOptionPane.showMessageDialog(jfc, "The file has invalid extension (." + ext + " needed).", "Error", JOptionPane.ERROR_MESSAGE);
            return defaults;
        }
        return t.getAbsolutePath();
    }

    public String getClassTablePath() {
        return classTablePath;
    }

    public void setClassTablePath(String classTablePath) {
        this.classTablePath = classTablePath;
    }

    public String getLexicTablePath() {
        return lexicTablePath;
    }

    public void setLexicTablePath(String lexicTablePath) {
        this.lexicTablePath = lexicTablePath;
    }

    public String getStateTablePath() {
        return stateTablePath;
    }

    public void setStateTablePath(String stateTablePath) {
        this.stateTablePath = stateTablePath;
    }

    public String getSourceCodePath() {
        return sourceCodePath;
    }

    public void setSourceCodePath(String sourceCodePath) {
        this.sourceCodePath = sourceCodePath;
    }

    public String getPriorityTablePath() {
        return priorityTablePath;
    }

    public void setPriorityTablePath(String priorityTablePath) {
        this.priorityTablePath = priorityTablePath;
    }

    public String getStackWriterTablePath() {
        return stackWriterTablePath;
    }

    public void setStackWriterTablePath(String stackWriterTablePath) {
        this.stackWriterTablePath = stackWriterTablePath;
    }

    public void addListener(Listener listener) {
        speaker.addListener(listener);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClassTableChoose;
    private javax.swing.JButton jButtonLexicTableChoose;
    private javax.swing.JButton jButtonPriorityTableChoose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonStackTableChoose;
    private javax.swing.JButton jButtonStateTableChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldClassTablePath;
    private javax.swing.JTextField jTextFieldLexicTablePath;
    private javax.swing.JTextField jTextFieldPriorityTablePath;
    private javax.swing.JTextField jTextFieldStackTablePath;
    private javax.swing.JTextField jTextFieldStateTablePath;
    // End of variables declaration//GEN-END:variables
}
